feat: 图片相关
Vanessa219/vditor pull request #1348
Opened 2023-01-07 04:16 UTC by heiyehk

- #1220 改善图片预览问题，增加options->preview->showImage: boolean控制是否双击预览
- 增加options->previewImage函数获取触发的图片节点，参数img: HTMLImageElement

链接相关
- 增加options-> link属性，options->open: boolean控制点击打开链接，intercept函数控制点击的链接，参数 url: string

2023-01-07 12:58 UTC, 88250 requested changes
请避免类似这样的格式化：

![image](https://user-images.githubusercontent.com/873584/211151776-8a2722d0-3c9f-4ef5-a62f-8ebb25547c6d.png)

2023-01-07 15:06 UTC, heiyehk commented
> 请避免类似这样的格式化：
> 
> ![图像](https://user-images.githubusercontent.com/873584/211151776-8a2722d0-3c9f-4ef5-a62f-8ebb25547c6d.png)

好的，我的失误，忘记这块改动丢弃

2023-01-07 15:14 UTC, heiyehk commented
> 请避免类似这样的格式化：
> 
> ![image](https://user-images.githubusercontent.com/873584/211151776-8a2722d0-3c9f-4ef5-a62f-8ebb25547c6d.png)

代码格式已恢复

2023-01-07 15:23 UTC, 88250 approved these changes

2023-01-11 16:27 UTC, Vanessa219 commented
README 里面还麻烦进行相应的修改。

2023-01-12 06:22 UTC, heiyehk commented
> README 里面还麻烦进行相应的修改，谢谢。

已增加本次pr的readme，并对原来的options.link.intercept重新命名为options.link.trigger，该函数并不会去做拦截操作，命名优化

2023-01-15 02:33 UTC, merged